minimumReleaseAgeExclude:
  - '@llamaindex/liteparse-darwin-arm64@2.10.1'
  - '@llamaindex/liteparse-darwin-x64@2.10.1'
  - '@llamaindex/liteparse-linux-arm64-gnu@2.10.1'
  - '@llamaindex/liteparse-linux-x64-gnu@2.10.1'
  - '@llamaindex/liteparse-linux-x64-musl@2.10.1'
  - '@llamaindex/liteparse-win32-arm64-msvc@2.10.1'
  - '@llamaindex/liteparse-win32-x64-msvc@2.10.1'
  - '@llamaindex/liteparse@2.10.1'
  - eslint@10.9.0
  - '@earendil-works/chord@1.0.1'
  - '@earendil-works/pi-agent-core@1.0.1'
  - '@earendil-works/pi-ai@1.0.1'
  - '@earendil-works/pi-codemode@1.0.1'
  - '@earendil-works/pi-coding-agent@1.0.1'
  - '@earendil-works/pi-mcp@1.0.1'
  - '@earendil-works/pi-telemetry@1.0.1'
  - '@earendil-works/pi-tui@1.0.1'
